---
# tasks file for gitlab-ci
#- debug: var=ansible_all_ipv4_addresses
#- debug: var=ansible_default_ipv4.address
- include_vars: ../../vars.yml
- include: install-docker.yml
- include: install-gitlab-ci.yml
- include: install-gitlab-runners.yml
- include: configure-gitlab-ci-with-runners.yml
#- include: install-gitlab-runners.yml
